from selenium import webdriver
import unittest
class TestAdmin410(unittest.TestCase):
    def test_TC410(self):
        driver = webdriver.Chrome("C:/chromedriver.exe")
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/user/signin")

        el = driver.find_element_by_name('email')
        el.send_keys("admin@lsbookstore.com")
        el = driver.find_element_by_name('password')
        el.send_keys("Sa!12345")
        el = driver.find_element_by_name('signin').click()
        
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/index")
        driver.find_element_by_css_selector("body > div > div > div:nth-child(1) > a").click()
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        el = driver.find_element_by_name('title')
        el.send_keys("Your Life")
        el = driver.find_element_by_name('author')
        el.send_keys("Khang Nguyen")
        el = driver.find_element_by_name('price')
        el.send_keys("20")
        el = driver.find_element_by_name('in-stock')
        el.send_keys("5")
        el = driver.find_element_by_name('description')
        el.send_keys("")
        driver.find_element_by_css_selector("body > div > form > button").click()
        result = driver.current_url
        self.assertEqual(result, "http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        driver.quit()
    def test_TC411(self):
        driver = webdriver.Chrome("C:/chromedriver.exe")
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/user/signin")

        el = driver.find_element_by_name('email')
        el.send_keys("admin@lsbookstore.com")
        el = driver.find_element_by_name('password')
        el.send_keys("Sa!12345")
        el = driver.find_element_by_name('signin').click()
        
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/index")
        driver.find_element_by_css_selector("body > div > div > div:nth-child(1) > a").click()
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        el = driver.find_element_by_name('title')
        el.send_keys("Your Life")
        el = driver.find_element_by_name('author')
        el.send_keys("Khang Nguyen")
        el = driver.find_element_by_name('price')
        el.send_keys("20")
        el = driver.find_element_by_name('in-stock')
        el.send_keys("5")
        el = driver.find_element_by_name('description')
        el.send_keys("Best for your Life")
        driver.find_element_by_css_selector("body > div > form > button").click()
        result = driver.current_url
        self.assertEqual(result, "http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        driver.quit()
    def test_TC412(self):
        driver = webdriver.Chrome("C:/chromedriver.exe")
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/user/signin")

        el = driver.find_element_by_name('email')
        el.send_keys("admin@lsbookstore.com")
        el = driver.find_element_by_name('password')
        el.send_keys("Sa!12345")
        el = driver.find_element_by_name('signin').click()
        
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/index")
        driver.find_element_by_css_selector("body > div > div > div:nth-child(1) > a").click()
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        el = driver.find_element_by_name('title')
        el.send_keys(" ")
        el = driver.find_element_by_name('author')
        el.send_keys("Khang Nguyen")
        el = driver.find_element_by_name('price')
        el.send_keys("20")
        el = driver.find_element_by_name('in-stock')
        el.send_keys("5")
        el = driver.find_element_by_name('description')
        el.send_keys("Best for your Life")
        driver.find_element_by_css_selector("body > div > form > button").click()
        result = driver.current_url
        self.assertEqual(result, "http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        driver.quit()
    def test_TC413(self):
        driver = webdriver.Chrome("C:/chromedriver.exe")
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/user/signin")

        el = driver.find_element_by_name('email')
        el.send_keys("admin@lsbookstore.com")
        el = driver.find_element_by_name('password')
        el.send_keys("Sa!12345")
        el = driver.find_element_by_name('signin').click()
        
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/index")
        driver.find_element_by_css_selector("body > div > div > div:nth-child(1) > a").click()
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        el = driver.find_element_by_name('title')
        el.send_keys("A B")
        el = driver.find_element_by_name('author')
        el.send_keys("Khang Nguyen")
        el = driver.find_element_by_name('price')
        el.send_keys("20")
        el = driver.find_element_by_name('in-stock')
        el.send_keys("5")
        el = driver.find_element_by_name('description')
        el.send_keys("Best for your Life")
        driver.find_element_by_css_selector("body > div > form > button").click()
        result = driver.current_url
        self.assertEqual(result, "http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        driver.quit()
    def test_TC414(self):
        driver = webdriver.Chrome("C:/chromedriver.exe")
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/user/signin")

        el = driver.find_element_by_name('email')
        el.send_keys("admin@lsbookstore.com")
        el = driver.find_element_by_name('password')
        el.send_keys("Sa!12345")
        el = driver.find_element_by_name('signin').click()
        
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/index")
        driver.find_element_by_css_selector("body > div > div > div:nth-child(1) > a").click()
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        el = driver.find_element_by_name('title')
        el.send_keys("YourLife ")
        el = driver.find_element_by_name('author')
        el.send_keys("Khang Nguyen")
        el = driver.find_element_by_name('price')
        el.send_keys("20")
        el = driver.find_element_by_name('in-stock')
        el.send_keys("5")
        el = driver.find_element_by_name('description')
        el.send_keys("Best for your Life")
        driver.find_element_by_css_selector("body > div > form > button").click()
        result = driver.current_url
        self.assertEqual(result, "http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        driver.quit()
    def test_TC415(self):
        driver = webdriver.Chrome("C:/chromedriver.exe")
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/user/signin")

        el = driver.find_element_by_name('email')
        el.send_keys("admin@lsbookstore.com")
        el = driver.find_element_by_name('password')
        el.send_keys("Sa!12345")
        el = driver.find_element_by_name('signin').click()
        
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/index")
        driver.find_element_by_css_selector("body > div > div > div:nth-child(1) > a").click()
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        el = driver.find_element_by_name('title')
        el.send_keys("!!@@##")
        el = driver.find_element_by_name('author')
        el.send_keys("Khang Nguyen")
        el = driver.find_element_by_name('price')
        el.send_keys("20")
        el = driver.find_element_by_name('in-stock')
        el.send_keys("5")
        el = driver.find_element_by_name('description')
        el.send_keys("Best for your Life")
        driver.find_element_by_css_selector("body > div > form > button").click()
        result = driver.current_url
        self.assertEqual(result, "http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        driver.quit()
    def test_TC416(self):
        driver = webdriver.Chrome("C:/chromedriver.exe")
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/user/signin")

        el = driver.find_element_by_name('email')
        el.send_keys("admin@lsbookstore.com")
        el = driver.find_element_by_name('password')
        el.send_keys("Sa!12345")
        el = driver.find_element_by_name('signin').click()
        
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/index")
        driver.find_element_by_css_selector("body > div > div > div:nth-child(1) > a").click()
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        el = driver.find_element_by_name('title')
        el.send_keys("12345")
        el = driver.find_element_by_name('author')
        el.send_keys("Khang Nguyen")
        el = driver.find_element_by_name('price')
        el.send_keys("20")
        el = driver.find_element_by_name('in-stock')
        el.send_keys("5")
        el = driver.find_element_by_name('description')
        el.send_keys("Best for your Life")
        driver.find_element_by_css_selector("body > div > form > button").click()
        result = driver.current_url
        self.assertEqual(result, "http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        driver.quit()
    def test_TC417(self):
        driver = webdriver.Chrome("C:/chromedriver.exe")
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/user/signin")

        el = driver.find_element_by_name('email')
        el.send_keys("admin@lsbookstore.com")
        el = driver.find_element_by_name('password')
        el.send_keys("Sa!12345")
        el = driver.find_element_by_name('signin').click()
        
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/index")
        driver.find_element_by_css_selector("body > div > div > div:nth-child(1) > a").click()
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        el = driver.find_element_by_name('title')
        el.send_keys("yourlife")
        el = driver.find_element_by_name('author')
        el.send_keys("Khang Nguyen")
        el = driver.find_element_by_name('price')
        el.send_keys("20")
        el = driver.find_element_by_name('in-stock')
        el.send_keys("5")
        el = driver.find_element_by_name('description')
        el.send_keys("Best for your Life")
        driver.find_element_by_css_selector("body > div > form > button").click()
        result = driver.current_url
        self.assertEqual(result, "http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        driver.quit()
    def test_TC418(self):
        driver = webdriver.Chrome("C:/chromedriver.exe")
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/user/signin")

        el = driver.find_element_by_name('email')
        el.send_keys("admin@lsbookstore.com")
        el = driver.find_element_by_name('password')
        el.send_keys("Sa!12345")
        el = driver.find_element_by_name('signin').click()
        
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/index")
        driver.find_element_by_css_selector("body > div > div > div:nth-child(1) > a").click()
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        el = driver.find_element_by_name('title')
        el.send_keys("YOURLIFE")
        el = driver.find_element_by_name('author')
        el.send_keys("Khang Nguyen")
        el = driver.find_element_by_name('price')
        el.send_keys("20")
        el = driver.find_element_by_name('in-stock')
        el.send_keys("5")
        el = driver.find_element_by_name('description')
        el.send_keys("Best for your Life")
        driver.find_element_by_css_selector("body > div > form > button").click()
        result = driver.current_url
        self.assertEqual(result, "http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        driver.quit()
    def test_TC419(self):
        driver = webdriver.Chrome("C:/chromedriver.exe")
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/user/signin")

        el = driver.find_element_by_name('email')
        el.send_keys("admin@lsbookstore.com")
        el = driver.find_element_by_name('password')
        el.send_keys("Sa!12345")
        el = driver.find_element_by_name('signin').click()
        
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/index")
        driver.find_element_by_css_selector("body > div > div > div:nth-child(1) > a").click()
        driver.get("http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        el = driver.find_element_by_name('title')
        el.send_keys("!!  @@")
        el = driver.find_element_by_name('author')
        el.send_keys("Khang Nguyen")
        el = driver.find_element_by_name('price')
        el.send_keys("20")
        el = driver.find_element_by_name('in-stock')
        el.send_keys("5")
        el = driver.find_element_by_name('description')
        el.send_keys("Best for your Life")
        driver.find_element_by_css_selector("body > div > form > button").click()
        result = driver.current_url
        self.assertEqual(result, "http://localhost/TH71-WebBanHangTrucTuyen/admin/addProduct")
        driver.quit()
if __name__ == '__main__':
 suite = unittest.TestLoader().loadTestsFromTestCase(TestAdmin410)
 unittest.TextTestRunner(verbosity=2).run(suite)
